/* 
CREATE MORE HALLS
MAKE PLAYER JUMP AND FALL WITH GRAVITY
GIVE OBSTACLES A COLLIDER
CREATE A AUTOPOPULATOR FOR THE WORLD                        DONE
CREATE CREATE A DESISION MAKING MOMENT AT THE END
GIVE THE PLAYER 2 LIVES TO HIT OBSTACLES
*/